In [67]:
import pandas as pd
import numpy as np

df = pd.read_csv("adult_with_headers (1).csv")

# View first rows
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [69]:
# Dataset shape
df.shape

(32561, 15)

In [71]:
df.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [75]:
df = df.replace(" ?", np.nan)
df.isnull().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     583
income               0
dtype: int64

In [77]:
#Handle Missing Values
for col in df.columns:
    if df[col].dtype == "object":
        df[col].fillna(df[col].mode()[0], inplace=True)

In [79]:
print(df.isnull().sum())

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [81]:
#2. Scaling Techniques
#Numerical Columns
num_cols = df.select_dtypes(include=['int64','float64']).columns

#a) Standard Scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df_standard_scaled = df.copy()
df_standard_scaled[num_cols] = scaler.fit_transform(df[num_cols])
print(df_standard_scaled.head())

        age          workclass    fnlwgt   education  education_num  \
0  0.030671          State-gov -1.063611   Bachelors       1.134739
1  0.837109   Self-emp-not-inc -1.008707   Bachelors       1.134739
2 -0.042642            Private  0.245079     HS-grad      -0.420060
3  1.057047            Private  0.425801        11th      -1.197459
4 -0.775768            Private  1.408176   Bachelors       1.134739

        marital_status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male
1   Married-civ-spouse     Exec-managerial         Husband   White     Male
2             Divorced   Handlers-cleaners   Not-in-family   White     Male
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female

   capital_gain  capital_loss  hours_per_week  native_country  income
0      0.148453      -0.21666       -0.035429   United-States   <=50K
1     -0.145920      -0.21666       -2.222153   United-States   <=50K
2     -0.145920      -0.21666       -0.035429   United-States   <=50K
3     -0.145920      -0.21666       -0.035429   United-States   <=50K
4     -0.145920      -0.21666       -0.035429            Cuba   <=50K

In [83]:
#b) Min-Max Scaling
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df_minmax_scaled = df.copy()
df_minmax_scaled[num_cols] = scaler.fit_transform(df[num_cols])
print(df_minmax_scaled.head())

        age          workclass    fnlwgt   education  education_num  \
0  0.301370          State-gov  0.044302   Bachelors       0.800000
1  0.452055   Self-emp-not-inc  0.048238   Bachelors       0.800000
2  0.287671            Private  0.138113     HS-grad       0.533333
3  0.493151            Private  0.151068        11th       0.400000
4  0.150685            Private  0.221488   Bachelors       0.800000

        marital_status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male
1   Married-civ-spouse     Exec-managerial         Husband   White     Male
2             Divorced   Handlers-cleaners   Not-in-family   White     Male
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female

   capital_gain  capital_loss  hours_per_week  native_country  income
0       0.02174           0.0        0.397959   United-States   <=50K
1       0.00000           0.0        0.122449   United-States   <=50K
2       0.00000           0.0        0.397959   United-States   <=50K
3       0.00000           0.0        0.397959   United-States   <=50K
4       0.00000           0.0        0.397959            Cuba   <=50K

In [85]:
# 3. Encoding Techniques
#One-Hot Encoding (for <5 categories)
df = pd.get_dummies(df, columns=['sex','race','relationship'])
print(df.columns)

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'capital_gain', 'capital_loss',
       'hours_per_week', 'native_country', 'income', 'sex_ Female',
       'sex_ Male', 'race_ Amer-Indian-Eskimo', 'race_ Asian-Pac-Islander',
       'race_ Black', 'race_ Other', 'race_ White', 'relationship_ Husband',
       'relationship_ Not-in-family', 'relationship_ Other-relative',
       'relationship_ Own-child', 'relationship_ Unmarried',
       'relationship_ Wife'],
      dtype='object')

In [87]:
print(df.columns)

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'capital_gain', 'capital_loss',
       'hours_per_week', 'native_country', 'income', 'sex_ Female',
       'sex_ Male', 'race_ Amer-Indian-Eskimo', 'race_ Asian-Pac-Islander',
       'race_ Black', 'race_ Other', 'race_ White', 'relationship_ Husband',
       'relationship_ Not-in-family', 'relationship_ Other-relative',
       'relationship_ Own-child', 'relationship_ Unmarried',
       'relationship_ Wife'],
      dtype='object')

In [89]:
#Label Encoding (for >5 categories)
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

cat_cols = ['workclass','occupation','native_country','education','marital_status']

for col in cat_cols:
    df[col] = le.fit_transform(df[col])
print(df.head())

   age  workclass  fnlwgt  education  education_num  marital_status  \
0   39          6   77516          9             13               4
1   50          5   83311          9             13               2
2   38          3  215646         11              9               0
3   53          3  234721          1              7               2
4   28          3  338409          9             13               2

   occupation  capital_gain  capital_loss  hours_per_week  ...  \
0           0          2174             0              40  ...
1           3             0             0              13  ...
2           5             0             0              40  ...
3           5             0             0              40  ...
4           9             0             0              40  ...

   race_ Asian-Pac-Islander race_ Black  race_ Other  race_ White  \
0                     False       False        False         True
1                     False       False        False         True
2                     False       False        False         True
3                     False        True        False        False
4                     False        True        False        False

   relationship_ Husband  relationship_ Not-in-family  \
0                  False                         True
1                   True                        False
2                  False                         True
3                   True                        False
4                  False                        False

   relationship_ Other-relative  relationship_ Own-child  \
0                         False                    False
1                         False                    False
2                         False                    False
3                         False                    False
4                         False                    False

   relationship_ Unmarried  relationship_ Wife
0                    False               False
1                    False               False
2                    False               False
3                    False               False
4                    False                True

[5 rows x 25 columns]

In [91]:
Pros and Cons of Encoding Methods
One-Hot Encoding

Pros
  No ordinal relationship created
  Works well for nominal data
Cons
  Increases number of columns
  cause high dimensionality

Label Encoding
Pros
  Simple and fast
  Does not increase number of columns
Cons
  May introduce false order between categories

SyntaxError: invalid syntax (1663881895.py, line 1)

In [93]:
#4. Feature Engineering
#Feature 1: Capital Difference
df['capital_diff'] = df['capital_gain'] - df['capital_loss']
print(df[['capital_gain','capital_loss','capital_diff']].head())

   capital_gain  capital_loss  capital_diff
0          2174             0          2174
1             0             0             0
2             0             0             0
3             0             0             0
4             0             0             0

In [95]:
#Feature 2: Work Intensity
df['work_intensity'] = df['hours_per_week'] * df['education_num']
print(df[['hours_per_week','education_num','work_intensity']].head())

   hours_per_week  education_num  work_intensity
0              40             13             520
1              13             13             169
2              40              9             360
3              40              7             280
4              40             13             520

In [97]:
#5. Feature Transformation
#Log Transformation for Skewed Feature
df['log_capital_gain'] = np.log1p(df['capital_gain'])
print(df[['capital_gain','log_capital_gain']].head())

   capital_gain  log_capital_gain
0          2174          7.684784
1             0          0.000000
2             0          0.000000
3             0          0.000000
4             0          0.000000